### ISSUE TITLE
Implement MetricLegendCategorical component

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/act-now-packages#124]
See [Figma - Metric Legend Categorical](https://www.figma.com/file/YN7x6bJmSfRHaovP5ABKu2/ActNow-Design-System?node-id=13%3A948)

![Image](https://user-images.githubusercontent.com/114084/187776415-7df0c37d-bf14-4a0d-b80d-5d0a7f259c83.png)

[Recommendations for components](https://www.dropbox.com/scl/fi/0kb074vxzz7dg9ju8vmas/Metric-Aware-Components.paper?dl=0&rlkey=ngr9ndis4sruq07kdqo2ont75#:uid=241396746348980555124289&h2=Recommendations-for-Components)

**Comment by smcclure17** [comment]
https://github.com/covid-projections/act-now-packages/pull/131/
