### ISSUE TITLE
Implement MetricSparklines

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/act-now-packages#167]
It should take two metrics, one for the bar chart (raw data series) and one for the line chart (normally a rolling average). We should also pass a number of days (or a date range) to filter the timeseries by, that way we can make multiple series consistent with each other.

```tsx
// width: 100% height: 100%, 
<MetricSparklines
  region={region}
  metricLineChart={metricCasesRollingAvg}
  metricBarChart={metricCases}
  numDays={30}
/>
```

![Image](https://user-images.githubusercontent.com/114084/189281931-c05c187b-7289-47d0-8c1f-cb4e3e481af1.png)

**Comment by smcclure17** [comment]
https://github.com/covid-projections/act-now-packages/pull/175
