### ISSUE TITLE
Investigate options to generate social images

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/act-now-packages#171]
In the past, social images have used location data and include both custom copy and charts or maps. We need to design a system that allows us to generate and host social images for each location page. For RA, we needed to generate multiple share images per page.

The components repo could have a few templates (correct size, paddings, etc), but tooling to generate/serve them might be better implemented in the template repo.

**Comment by smcclure17** [comment]
Investigation/proposal to build stand-alone redirect/share link service: https://www.dropbox.com/scl/fi/dvfdft2opsp1syuolccx3/Act-Now-Share-Links.paper?dl=0&rlkey=pimu8w95ys98d07h8sn0z2knz

Super simplistic share link prototype: https://github.com/smcclure17/redirect-demo

Options for act now share images: https://www.dropbox.com/scl/fi/bx2xn0a9c2vekrq2j0pt0/Act-Now-Dynamic-Share-Pages.paper?dl=0&rlkey=b43zq3rijzk54ly25t95qod53
