### ISSUE TITLE
Possible bug: Sorting CompareTable crashes when the cells use the useData hook

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/act-now-packages#177]
I'm working on implementing a metric-aware compare table, which renders fine initially, but it crashes if we attempt to sort the table (even if we don't sort by metric).

## Notes 

- Sorting works just fine for non-metric aware components (See storybook - https://act-now-packages--pr166-pablo-sortable-table-izav3d8y.web.app/storybook/index.html?path=/story/table-comparetable--example)
- I haven't figured out a good pattern to access MetricData from the `compareFn` of each column, so I set the sorting function to be by population of the region. One option could be to fetch metric data for all the regions and metrics up-front and include the data on the row data items, I tried that and the table still crashes. 

I suspect that this might be due to a race condition between the compare table internal state and the state of the mock data provider, but I'm not sure.

## How to Test

- Using Storybook https://act-now-packages--pr178-pablo-examples-compa-3fppwcmo.web.app/storybook/index.html?path=/story/metrics-metriccomparetable--example (it also crashes with metrics that use the mock data metric provider)

Using the hackathon repo:

- Use this branch https://github.com/covid-projections/act-now-packages/pull/166 and link `ui-components`
- On the hackathon repo, link `@actnowcoalition/ui-components`
- Add the MetricCompareTable to the homepage, adding all the states as regions and all the available metrics

```tsx
import { MetricCompareTable } from '@actnowcoalition/ui-components';

// ...
<MetricCompareTable
  regions={states.all}
  metrics={metricsCatalog.metrics}
/>
```

Note that the table will render correctly, but when we try to sort the table (even if we sort by location name), the table will crash.

**Comment by mikelehen** [comment]
Fixed by #182
