### ISSUE TITLE
Implement overview banner

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/act-now-packages#199]
[Figma - ActNow Design System](https://www.figma.com/file/YN7x6bJmSfRHaovP5ABKu2/ActNow-Design-System?node-id=32%3A5611)

![Image](https://user-images.githubusercontent.com/114084/191078506-87b0d51b-59d8-4c8e-8f8e-cd580a826e63.png)

**Comment by mikelehen** [comment]
I think we opted not to do this.
