### ISSUE TITLE
Try to unify levelSet and categories for COMMUNITY_RISK_LEVEL metric.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/act-now-packages#259]
See https://github.com/covid-projections/hackathon-september-2022/pull/3/files#diff-ce3a93efd046e7a95d61484997047a9987f83e8947ca7abfdd6f3669cfed455eR97

Basically to set up the COMMUNITY_RISK_LEVEL metric in the hackathon, I had to specify a levelSet so that we could render a thermometer for it, and also categories (so that the 0,1,2 values could be rendered as Low,Medium,High and colored correctly).

This feels kinda' redundant / hacky.  I'm wondering if we could make the thermometer fall back to rendering from the categories or something.  Or maybe categories should be tied to levels somehow (you specify a value and a level instead of value,label,color)?  Not sure.

**Comment by pnavarrc** [comment]
I have been thinking about this recently, I think we could consolidate the notion of level for metrics with categories and thresholds

- Levels have a color, a name and a description or extended name
- There is a notion of order in the levels. For example: _high risk_ to _low risk_, or _high_, _medium high_, _medium low_, and _low income_ for categorical, and levels sorted by thresholds in the case of threshold metrics
- In both cases we have a "default" or "missing data" level that will likely be treated differently in the UI (it shouldn't be part of the thermometer, for example)
- Both types of metrics should have a way to resolve a level given metric data

We could update `MetricCategory` to be defined in terms of `MetricLevel` objects, and separate the default level from the ordered sequence of levels for the metric.

**Comment by mikelehen** [comment]
👍 to all of that. I think it's worth trying and we can see how it looks!
