### ISSUE TITLE
MetricLegendThreshold should not show the "default/missing data" level

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/act-now-packages#304]
In https://github.com/covid-projections/act-now-packages/pull/299, we enabled `MetricLegendThreshold` to be used with metrics with categories (and not only with metrics with levels and thresholds). This caused the legend for the community risk level map to show the default level in the legend:

![Image](https://user-images.githubusercontent.com/114084/196295625-9b3fd41e-15e6-4a13-b126-d299e9aa1437.png)

We should have a better way to handle this, maybe we could filter out category items with a `nil` value?

**Comment by pnavarrc** [comment]
I think this is fixed?

**Comment by mikelehen** [comment]
Oh, yes.  I might have resolved this with #259.
