### ISSUE TITLE
Implement JSON Data Provider

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/act-now-packages#377]
Can we get example JSON from @chasulin  and @faihegberg  (and anybody else that ran into this?)

**Comment by smcclure17** [comment]
Not examples from real use cases, but possible forms to consider could maybe be: 

Record style, e.g:
```json
{
  "data": [
    {"region": "USA", "metric1:" "value"},
    {"region": "CAN", "metric1:" "value"},
    ...
  ]
}
```

Region/entity indexed (like the output of lodash's `keyBy()`):
```json
{
  "USA": {"metric1": "value"}, 
  "CAN": {"metric2": "value"},
  ...
}
```

Metric indexed:
```JSON
{
  "metric1": {"USA":"value", "CAN":"value"}
  "metric2": {"USA":"value2", "CAN":"value2"}
  ...
}
```

Maybe there's a world in which we can pass an "example" or "template" structure to the provider, and the provider could use that template to parse the actual file? Not sure what that would take to implement...

**Comment by pnavarrc** [comment]
I think that something that mimics the structure of the CSV could work (so record style?)

```json
{
  "data": [
    { "region": "CAN", "date": "2020-01-01", "metric1": 1.23, "metric2": 1.34 },
  ]
}
```

I'm not sure if we need the "data" key in the JSON (it could just be an array), but we could make the provider configurable so we can tell how to access the array. Open to more ideas of course!

In general I like to organize data using the principles in [Tidy Data](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html) (basically the CSV format that we use for the `CSVDataProvider`). 

- https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html
- https://www.jstatsoft.org/article/view/v059i10

**Comment by smcclure17** [comment]
That makes sense--I agree, I'll start with this. 

Thinking out loud, Python Pandas has a [JSON loader with an "orient" option](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html) that can accept multiple formats--maybe we could (eventually) model this to be similar? I think it's best to prioritize one or two formats to start with, though. And, TBH, I've always found importing JSON into Pandas a little finicky

**Comment by smcclure17** [comment]
#465

**Comment by pnavarrc** [comment]
One idea to make it a bit more generic could be to pass an optional `transform` function that takes the entire JSON object and returns the array of objects. This could be used to grab arrays that are nested in the JSON, filter out data, simplify the objects, etc.

```ts
const jsonData = {
  states: {
    data: [
      /* rows */
    ]
  }
}

const provider = new JsonDataProvider(PROVIDER_ID, {
  regionDb: states,
  regionColumn: "region",
  dateColumn: dateCol,
  jsonData: jsonData,
  transform: (json) => {
    return json.states.data
      .filter(row => row.region.length !== 2);  
  }
});
```

That being said, I would punt on that until we need it.

**Comment by mikelehen** [comment]
I like this idea!  It saves you from having to write a little script that reads JSON and exports it again...  though in some cases it might be better to do it in a script to reduce the file size and processing that needs to happen during page loads.  Though you could always create a snapshot to avoid that. 🤷

**Comment by mikelehen** [comment]
We could do something similar for CSV files if you want to restructure columns or pre-process any of the data, etc.
