### ISSUE TITLE
Implement ErrorBoundary and Loading states for our components

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/act-now-packages#385]
Some of our components have a loading state, but not all of them. Having a good loading state will prevent layout shift and tells the user that something will show up.

Error boundaries contain errors and prevent them from breaking the entire page, we should implement those too https://reactjs.org/docs/error-boundaries.html

**Comment by mikelehen** [comment]
I added storybook stories for error / loading state testing and opened individual bugs for loading state / error improvements.  See #280, #417, #418, #419, #421, #422

I'm going to close this and open a new bug just about ErrorBoundary which I think is its own task.
