### ISSUE TITLE
Improve handing of minValue, maxValue in charts

### ISSUE THREAD

**Issue by pnavarrc** [covid-projections/act-now-packages#386]
We have a few places where we want to set minValue, maxValue in the charts

- The metric might have a defined minValue and maxValue
- The timeseries will have minValue, maxValue
- In some cases, the type of data could have a specific natural range (vaccination, 0% - 100%)
- A specific visual representation might require start from 0 (Bar Chart)
- The minValue and maxValue could be contextual (we want to start at 0 in some cases, but at the min value in other cases)

We need to investigate a way to make the behaviors more consistent across charts. For example, we could have an order of precedence on how the minValue, maxValue are taken from (component props, timeseries, metric definition)

**Comment by faihegberg** [comment]
Here's the [doc](https://www.dropbox.com/scl/fi/zmykem7z5r1plryn79r6a/minValue-and-maxValue-in-Charts.paper?dl=0&rlkey=wzsfi96zd9y5ffctkhjuc1zcj) documenting the current and new implementation.
