### ISSUE TITLE
Labels for chart lines

### ISSUE THREAD

**Issue by faihegberg** [covid-projections/act-now-packages#416]
Currently charts in our package don't contain line labels. It would be good to explore whether adding line labels (like in the screenshot below, taken from CAN site) would be useful.

![](https://paper-attachments.dropboxusercontent.com/s_666181A427B0C9C48007E94AA3342DB336440C41F4A8211BA472074BB40968AE_1668707135306_image.png)

**Comment by pnavarrc** [comment]
Should be part of the Trends chart.

**Comment by mikelehen** [comment]
Pablo implemented this!
