### ISSUE TITLE
Add generic glossary-like page structure

### ISSUE THREAD

**Issue by faihegberg** [covid-projections/act-now-packages#429]
CAN's learn page has a glossary-like page structure which might be useful as a generic template. Specifically, a simple page with vertical navigation menu, where clicking each menu item would scroll to its corresponding section of the page.

![Image](https://user-images.githubusercontent.com/46338131/203176778-b9e2cdfc-5051-4b65-b78f-6559ca26c90c.png)

**Comment by pnavarrc** [comment]
We can implement this when someone asks for it.
