### ISSUE TITLE
Compare table: Better loading state

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/act-now-packages#473]
We don't have a loading state for the compare table.  We should, but I'm not sure how to get the width / height.  It looks like right now (for our storybook examples at least) we size the table through `sx` property.  Maybe we need to pass this through to `Skeleton` or something.

**Comment by mikelehen** [comment]
So in StoryBook, we wrap the compare table in a container:

```
  <TableContainer sx={{ maxWidth: 600, height: 500 }}>
    <MetricCompareTable {...args} />
  </TableContainer>
```

This is sufficient to prevent layout shifts, since the size/height is specified on the container.  But I'm not 100% sure if this will always be the case.  If it's not, then we need to figure out how to display a suitable loading state in the table itself.  Need to sync with @pnavarrc .

**Comment by pnavarrc** [comment]
I think that the `TableContainer` is good enough for now. We could have a nicer loading state, but that's probably low priority for now.

**Comment by pnavarrc** [comment]
actually I'm going to implement a simple loading state so it looks better while loading
