### ISSUE TITLE
MUI `Link` styling regression with updated `@emotion/` and `@mui/` packages

### ISSUE THREAD

**Issue by smcclure17** [covid-projections/act-now-packages#486]
## Context:
`@mui/lab` was added as a dependency and versions of `@emotion/react` `@emotion/styled` and `@mui/material` were bumped in order to use the MUI Lab [Tabs API](https://mui.com/material-ui/react-tabs/#experimental-api) when implementing `MetricChartTabs` (PR #479). 

## Issue: 

Presumably, updating package versions broke/changed the use of MUI `createStyled()` on the MUI `Link` component. No other components were affected: 

    .../MetricCompareTable.style.ts(12,14): error TS2742: The inferred type of 'StyledLink' cannot be named without a reference to '@mui/system/node_modules/csstype'. This is likely not portable. A type annotation is necessary.

VSCode is still able to infer the type:
![](https://user-images.githubusercontent.com/55333380/207084258-3659bc92-b681-4d9a-85d3-50fa8e5d140d.png)

but the build failed. Per the error, adding an explicit (though incomplete) type annotation fixed the build, but this doesn’t feel like a satisfactory solution and doesn’t get at the root cause of the issue. Removing the styled component and adding styles inline also circumvented the issue. 

## Package Updates:
| package         | old version | new version      |
| --------------- | ----------- | ---------------- |
| @emotion/react  | ^11.9.3     | ^11.10.5         |
| @emotion/styled | ^11.9.3     | ^11.10.5         |
| @mui/material   | ^5.9.1      | ^5.10.17         |
| @mui/lab        | --          | ^5.0.0-alpha.111 |

**Comment by pnavarrc** [comment]
Maybe this will go away after solving https://github.com/covid-projections/act-now-template/issues/77 - let's hold until that's solved.

**Comment by mikelehen** [comment]
I'm not 100% sure what the issue is, but if you delete `yarn.lock` in `packages/ui-components` and run `yarn` again to regenerate it, the problem goes away.

**Comment by pnavarrc** [comment]
oh awesome!

**Comment by pnavarrc** [comment]
See https://mui.com/material-ui/guides/typescript/#complications-with-the-component-prop - In some cases, you need to cast the type after customizing its styles (they use a different syntax to style the button, but the idea is the same)

```tsx
import Button from '@mui/material/Button';
import { styled } from '@mui/material/styles';

const CustomButton = styled(Button)({
  // your custom styles go here
}) as typeof Button;

```
