### ISSUE TITLE
Clean up github org / repos.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/act-now-packages#498]
I suggest we:
* Rename covid-projections (the org) to act-now-coalition
* Rename covid-projections (the repo) to covid-act-now-website
* Do a quick sanity-check through the README.md's in our public repos for anything egregiously wrong / confusing.  Perhaps also add links to https://www.actnowcoalition.org/ to tie everything together.

The "hard" part" of this is making sure we don't break anything.  I think github is pretty forgiving about automatically redirecting after renames, but I'd talk to Pablo first.  Also, maybe run this whole plan past everybody at standup to make sure people are on board with the names, etc.

**Comment by faihegberg** [comment]
Docs for reference
- https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization
- https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository
