### ISSUE TITLE
Markdown bug

### ISSUE THREAD

**Issue by chasulin** [covid-projections/act-now-packages#51]
_Description in progress_

When we try to use the Markdown component using the template (or hackathon) repository, Next.js throws an error (ESM). It looks like this error is caused by Next not handling ESM-only packages correctly (react-markdown is ESM-only).

We need to find a workaround to be able to implement and use the Markdown component.

# Notes

- https://github.com/vercel/next.js/issues/30330#issuecomment-952847838

**Comment by mikelehen** [comment]
See also https://github.com/covid-projections/hackathon-july-2022/pull/9
