### ISSUE TITLE
Write CanDataProvider

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/act-now-packages#87]
I'm not sure what kind of data provider we’d want in order to fetch data from the CAN API.

Ideally it’d be able to fetch data for one region at a time (rather than all states/counties/etc. at once) which I think means using the JSON endpoints.  Though maybe it could just use the timeseries CSV endpoints?

I’m not sure if there’s a generic JsonDataProvider we could create that would be flexible enough to work with the CAN API, so it might make sense to just write a bespoke CanDataProvider to start and then see if there’s anything we can generalize from that.

This isn't exactly urgent, but I think would be a useful exercise and will let us use CAN data in our hackathons.

**Comment by mikelehen** [comment]
Sean completed this.

**Comment by smcclure17** [comment]
whoops, thanks @mikelehen for closing this 🙏
